name: Main CI workflow
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ./Library
          key: Library-gravity-direction-pack-TargetPlatform_ANY
          restore-keys: |
            Library-gravity-direction-pack-
            Library-

      - uses: game-ci/unity-test-runner@v2
        id: myTestStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: ${{ steps.myTestStep.outputs.artifactsPath }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.myTestStep.outputs.coveragePath }}
