name: GitHub Actions Demo
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: script
        shell: bash
        run: |
          pwd
          ls -lah ./

      - uses: actions/cache@v2
        with:
          path: /home/runner/work/gravity-direction-pack/gravity-direction-pack/Library
          key: Library-gravity-direction-pack-TargetPlatform_ANY
          restore-keys: |
            Library-gravity-direction-pack-
            Library-

      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: /home/runner/work/gravity-direction-pack/gravity-direction-pack
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.myTestStep.outputs.coveragePath }}